// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CohnectSDK.Buffers
{

public enum ClientMessageType : ushort
{
  PING_SUCCESS = 0,
  SESSION_START_SUCCESS = 1,
  SESSION_START_FAILED = 2,
  SESSION_END_SUCCESS = 3,
  SESSION_END_FAILED = 4,
  EVENT_SUCCESS = 5,
  EVENT_FAILED = 6,
  NOTIFICATION = 7,
};


}
