// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CohnectSDK.Buffers
{

public enum RequestOp : ushort
{
  GET = 0,
  SET = 1,
  SET_CLIENT_TAGS = 2,
  EXECUTE = 3,
  SUBSCRIBE = 4,
  BROADCAST = 5,
};


}
