// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CohnectSDK.Buffers
{

public enum RequestOp : ushort
{
  PING = 0,
  SESSION_START = 1,
  SESSION_END = 2,
  EVENT = 3,
  REGISTER_CLIENT_TAGS = 4,
};


}
